### PR TITLE
Uninstall fix

### PR DESCRIPTION
**Pull request by solbu**
This fixes the uninstall issue.
It close issue #48 

For some reason it has 6 commits,. when I really only have 2. Oh well.

### CODE REVIEW

**Comment by andy5995** [comment]
Do you think it would be better if hldig.conf was installed to SYSCONFDIR instead, and exempt from removal?

**Comment by solbu** [comment]
I would support that.
In Mageia, and Mandriva when it existed, we do that. We install the config files in /etc/hldig/

```
rpm -qlp RPMS/x86_64/hldig-0.1.01-1.solbu5.x86_64.rpm |grep /etc
/etc/hldig
/etc/hldig/HtFileType-magic.mime
/etc/hldig/cookies.txt
/etc/hldig/hldig.conf
/etc/hldig/mime.types
```
To achieve this, we configure using amongst others, these configure options:
```
--with-config-dir=%{_sysconfdir}/hldig
--with-default-config-file=%{_sysconfdir}/hldig/hldig.conf
```
(%{_sysconfdir} is an rpm variable that expands to «/etc»

So changing to SYSCONFDIR/hldig would be nice.

**Comment by andy5995** [comment]
>So changing to SYSCONFDIR/hldig would be nice.

Ok, I'll merge this so we can move forward a little. Can you make that change in a separate PR or would you like me to?

**Comment by solbu** [comment]
I've already made some changes. 
Will send a PR later today.

**Pull request merged**
