### PR TITLE
Don't ship compiled translations.

### PR DESCRIPTION
**Pull request by solbu**
in po/, *.gmo and .mo files are auto-generated on compile stage, unless they already exist.
In which case updated translations will not be used, as it is the compiled file that gettext used for displaying strings.

Shipping these files is a mistake.

### CODE REVIEW

**Comment by andy5995** [comment]
Considering GNU wrote the book on gettext, and ship gmo files with coreutils, and other packages such as bash include them, I don't see any problem.

**Comment by solbu** [comment]
The upstream Gettext maintainers do not ship these files, and they maintain the tool to generate them.

Here is a direct lnk to their .gitignore in the official git repo. THe fisrts ignore lines are in line 456:
http://git.savannah.gnu.org/cgit/gettext.git/tree/.gitignore

**Comment by solbu** [comment]
And no, coreutils Do Not include these files in the repository.
Here is a link to coreutils official git repo. the gmo files are listed in line 147 in .gitignore:
http://git.savannah.gnu.org/cgit/coreutils.git/tree/.gitignore

**Comment by solbu** [comment]
Having these files in version control is wrong.

**Comment by andy5995** [comment]
They also have files such as THANKS, ABOUT-NLS, configure, and various source code headers listed in that file

Take a look at one of their released source tarballs https://ftp.gnu.org/gnu/coreutils/coreutils-8.26.tar.xz

**Pull request closed without merging**
