### PR TITLE
Don't ship .gmo files, they are auto generated on compile stage

### PR DESCRIPTION
**Pull request by solbu**
in po/, *.gmo and .mo files are auto-generated on compile stage, unless they already exist.
In which case updated translations will not be used, as it is the compiled file that gettext used for displaying strings.

Shipping these files is a mistake.
I have also added two lines in .gitignore to prevent this in the future.

### CODE REVIEW

**Comment by andy5995** [comment]
When I remove the gmo files, and then re-run configure && make && make install, I get this..

>/usr/bin/install: cannot stat './nl_NL.gmo': No such file or directory
installing ./nl_NL.gmo as /home/andy/src/hldig/testing/share/locale/nl_NL/LC_MESSAGES/hldig.mo
/usr/bin/install: cannot stat './ru.gmo': No such file or directory
installing ./ru.gmo as /home/andy/src/hldig/testing/share/locale/ru/LC_MESSAGES/hldig.mo

**Comment by solbu** [comment]
I just tested, and I don't have this error.

**Comment by andy5995** [comment]
Hmm.. interesting.. and I see that problem doesn't happen on travis either. Strange.. the build commands are the same on travis (specified in .travis.yml) as on my system.

But I am even more confused about this: I see that even a source package like GNU coreutils is shipped with the gmo files.

**Comment by solbu** [comment]
Screw it, I'm doing it again! (Damn you github!)

**Pull request closed without merging**
