### PR TITLE
issue 81 css

### PR DESCRIPTION
**Pull request by jamessouth**

### CODE REVIEW

**Comment by solbu** [comment]
I'm sure the changes to the web page files could be in the same PR. :-)

**Comment by jamessouth** [comment]
ok thanks

**Comment by andy5995** [comment]
>I'm sure the changes to the web page files could be in the same PR. :-)

Yes. @jamessouth , normally how I can review and test a pull request is by merging the patch locally. When related patches like this are spread among several, it's much more challenging to visualize the end result.

I get a good impression from what I see so far, looks like you're definitely on the right track!

Could you put all of your changes onto a separate branch, and open a new PR? Or if it's easier, it's fine to use a branch you've already created, and whichever PR you used to push the branch will get updated automatically.

Thank you for working on this! I'm looking forward to seeing the final result.

**Comment by jamessouth** [comment]
ok sorry guys, what's the best way to clean this up? i see that i can close the PR, there are the amend and rebase commands to remove the file from the commit, or you can apparently remove it in a new commit, i guess that would leave an empty PR? then you close it? the new body content file i created and pushed is no longer on my local system, which is unexpected to me. i have that work backed up in another file and it's sitting in the PR, but how do i get that new file back?

**Comment by andy5995** [comment]
>what's the best way to clean this up?

From the develop branch, check out a new branch (issue_81 ... make sure the branch doesn't already exist).

now you're going to merge in your 3 branches. Ignore the branch from #96 and note the comment I left on that ticket. The content for index is in infiles/index.sct and I think that's what you were looking for. If you still need to edit that file, make that edit after you merge in the other 3 branches.

issue_81_style, tail and default

While on the new branch you created

`git merge issue_81_style_css`

And do that for the other 2.

Then edit infiles/index.sct if necessary.

It's preferred that you test your changes by running simplecgen to generate the web site:

https://github.com/andy5995/hldig/blob/25a16cec4e4c220240643c4cbe44be07b9a0e88b/docs/README#L20

But since you're web designer, not a software developer, I'm not sure I should expect you to install the build tools.

If you're on Linux, and want to try, it's pretty simple.

Otherwise, you can bypass testing your changes. 

Commit after you've merged in the 3 branches and edit the index.sct file. Then push the branch, make the PR.

You can pop onto IRC chat at anytime if you get stuck, or just to see what's happening:

http://webchat.freenode.net/?channels=%23hldig&uio=d4

**Comment by jamessouth** [comment]
merged into #100, so closing

**Pull request closed without merging**
